[project]
name = "auto-detect-exceptions"
version = "0.1.0"
description = ""
authors = [
    { name = "lucemia", email = "lucemia@gmail.com" },
]
readme = "README.md"

[tool.poetry]
packages = [
    { include = "auto_detect_exceptions", from = "src" }
]

[project.scripts]
detect1 = "auto_detect_exceptions.cli:main"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
